galaxy_info:
  author: "Michal Siemianowski"
  description: "TPICAP CIS Baseline"
  company: "TPICAP"
  license: MIT
  min_ansible_version: 2.2

  platforms:
  - name: EL
    versions:
      - 7

  galaxy_tags:
    - system
    - security
    - cis
    - hardening

dependencies: []
