---
- name: Gather Information
  hosts: all
  become: yes
  vars:
    log_timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"

  tasks:
    - name: Create log directory on Ansible control machine (localhost)
      local_action:
        module: file
        path: "/root/cfgmain/patching/prepatch/logs/{{ ansible_date_time.date }}/{{ ansible_hostname }}/{{ log_timestamp }}"
        state: directory
        recurse: yes

    - name: Execute commands and capture output
      shell: "{{ item }}"
      loop:
        - "ifconfig -a"
        - "ip a s"
        - "netstat -rn"
        - "cat /etc/fstab"
        - "mount"
        - "df -h"
        - "rpm -qa"
        - "ps -ef"
        - "uptime"   
        - "uname -r"
        - "crontab -l -u root"
        - "yum list kernel"
      register: command_result
      ignore_errors: yes

    - name: Save command outputs as log files
      copy:
        content: "{{ item.stdout }}"
        dest: "/root/cfgmain/patching/prepatch/logs/{{ ansible_date_time.date }}/{{ ansible_hostname }}/{{ log_timestamp }}/{{ item.item.split(' ')[0] }}.log"
      loop: "{{ command_result.results }}"
      delegate_to: localhost
