#!/bin/bash

# OSPrepatching script will determine the current kernel installed
# If server is not register it will auto register

host=$@

for i in $host
do
        #echo Checking if $i is pingable
        hostchk=`ping -c1 $i`
                if [[ $? -eq 0 ]]
                then

                hostssh=`ssh -tt -o BatchMode=yes -o StrictHostKeyChecking=no -q $i date`

                        if [[ $? -eq 0 ]]
                        then
                                ssh -q $i "realm permit -g corp-itsecurity-srvcs-linux"
                        else
                                echo $i: host is not accessible via ssh or passwordless ssh as root not allowed
                        fi
                else
                        echo $i: host not pingable
                fi
done
