#!/bin/bash

# Display secscan-a account info if found
# Add qualys account automatically if not found
# Check if server is accessible via ssh as root or if server is pingable
# Exit if password prompt found during ssh (quickie exit to move to the next server)
# Filter if server or IP resolvable

host=$@
for i in $host
do
        #echo Checking if $i is pingable
        hostchk=`ping -c1 $i`
                if [[ $? -eq 0 ]]
                then

                hostssh=`ssh -tt -o BatchMode=yes -o StrictHostKeyChecking=no -q $i date`

                        if [[ $? -eq 0 ]]
                        then
			echo -n "$i: "; ssh -q -tt $i  'redhatrelease=/etc/redhat-release ; if [ -f "$redhatrelease" ]; then  cat "$redhatrelease"; else suserelease=/etc/SuSE-release ; if [ -f "$suserelease" ]; then  echo `cat $suserelease` ; else solarisrelease=/etc/release ; if [ -f "$solarisrelease" ] ; then echo `uname -va | cut -d " " -f 1,3` ; else echo file not found;fi ; fi  ; fi'
#echo -n "$i: "; ssh -q -tt $i  'redhatrelease=/etc/redhat-release ; if [ -f "$redhatrelease" ]; then  cat "$redhatrelease"; else suserelease=/etc/SuSE-release ; if [ -f "$suserelease" ]; then  echo `cat $suserelease` ; else     ubunturelease=/etc/issuee ; if [ -f "$ubunturelease" ]; then  echo `cat $ubunturelease | cut -d " " -f 1-3 | head -n 1` ; else solarisrelease=/etc/release ; if [ -f "$solarisrelease" ] ; then echo `uname -va | cut -d " " -f 1,3` ; else echo file not found;fi ; fi  ; fi'

                        else
                                echo $i: host is not accessible via ssh or passwordless ssh as root not allowed
                        fi
                else
                        echo $i: host not pingable
                fi
done
