#!/bin/bash

usage() {
    echo "Usage: $0 [-h] [-f FILE | HOSTNAME]"
    echo "  -h: Display this help message"
    echo "  -f FILE: Specify a file containing a list of hosts (one per line)"
    echo "  HOSTNAME: Specify a single hostname to check"
    exit 1
}

check_ping() {
    ping -c 1 -W 1 "$1" > /dev/null 2>&1
    return $?
}

check_ssh_and_process() {
    ssh -o ConnectTimeout=5 "$1" "pgrep ds_agent > /dev/null 2>&1"
    return $?
}

if [ $# -eq 0 ]; then
    usage
fi

FILE=""
HOST=""
IS_FILE=false

while getopts ":hf:" opt; do
    case $opt in
        h)
            usage
            ;;
        f)
            FILE=$OPTARG
            IS_FILE=true
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done

shift $((OPTIND-1))

# If a file is provided, read hosts from the file
if $IS_FILE; then
    if [ ! -f "$FILE" ]; then
        echo "File not found: $FILE"
        exit 1
    fi
    while IFS= read -r host; do
        if check_ping "$host"; then
            echo "Host $host is pingable."
            if check_ssh_and_process "$host"; then
                echo "ds_agent process is running on $host."
            else
                echo "ds_agent process is NOT running on $host."
            fi
        else
            echo "Host $host is not pingable."
        fi
    done < "$FILE"
# If a single hostname is provided, check it directly
elif [ $# -eq 1 ]; then
    HOST=$1
    if check_ping "$HOST"; then
        echo "Host $HOST is pingable."
        if check_ssh_and_process "$HOST"; then
            echo "ds_agent process is running on $HOST."
        else
            echo "ds_agent process is NOT running on $HOST."
        fi
    else
        echo "Host $HOST is not pingable."
    fi
else
    echo "Invalid number of arguments."
    usage
fi

