# tasks file for qualys_cloud_agent deployment

  - name: verify if this is RHEL6
    shell: cat /etc/system-release | sed 's/[^0-9.]//g'
    register: osresult

  - name: Create svcqca Group
    group:
      name: svcqca
      gid: 2708

  - name: Create svcqca User
    user:
      name: svcqca
      uid: 2708
      group: svcqca
      comment: "Qualys Cloud Agent Service Account"
      home: "/home/svcqca"
      shell: /bin/bash
      password: "$6$lNK6g1B7$Miw5TpHbjPxW2lOhxAitfb22saRUH0W9dMuubcmLUzg2isiN5agVCL8MjSJrmMd5PEoPkknyZzGiWQbGKJUep/"

  - name: Add Qualys SSH-Key
    authorized_key:
      user: svcqca
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrOOi3cMubz5DTl85EIho6zJDNjBBcp6H1CXmYfgiXKr/XhqgyCOgCPJof7ikvleikm2UE5J7KiIRyvN0LvPDXe3dz1xGEm/sy7lLGyMQUFF0GnTDsFVeEYx6703U/m0kUgRquBP1UCD6KWnplVzHA+chBK9xLrojxteanbZ8jTW3I07HzzvT9ygiNkHF2IPW9f5vWeqkDqhMcNGjh1UDIPFajTd1W73BKr5R4uk3AetCO0PbcYVF5fjVkGEDyw9/m1ZjUQK/T7Bhv1mkGgz7dsAQnT5h74T22EblNvALL8fe/8QoSgKRD3GosRN5JtNvyJ6xiK7O5Ux6azK2tmtQf"

  - name: Configure sudoers
    copy:
      src: sudoers_qualys
      dest: /etc/sudoers.d/
      owner: root
      group: root
      mode: 0755

  - name: Copy Qualy Cloud Agent package to server
    copy:
      src: qualys-cloud-agent.x86_64.rpm
      dest: /var/tmp/qualys-cloud-agent.x86_64.rpm

  - name: Install Qualys Cloud Agent from Common Tools
    yum:
      name: /var/tmp/qualys-cloud-agent.x86_64.rpm
      state: present
      disable_gpg_check: true

  - name: Change ownership to qualys cloud agent service account
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: svcqca
      group: svcqca
    with_items:
      - /etc/qualys
      - /usr/local/qualys

  - name: get environment
    shell : hostname | cut -c1-2
    register: envresult1

  - name: Activate Qualys Cloud Agent to AMER
    command: /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=4cbf2459-cb83-4d1a-8364-a4415508bd68 CustomerId=b546b3c9-3885-53eb-e040-18ac09046184 User=svcqca LogLevel=3 UseSudo=1 SudoUser=svcqca UserGroup=svcqca
    when: ( envresult1.stdout == 'us' ) or ( envresult1.stdout == 'va' ) or ( envresult1.stdout == 'nj')

  - name: Activate Qualys Cloud Agent to EMER
    command: /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=0bfc6401-4fa2-4175-9cc2-fb8070f75e9a CustomerId=b546b3c9-3885-53eb-e040-18ac09046184 User=svcqca LogLevel=3 UseSudo=1 SudoUser=svcqca UserGroup=svcqca
    when: ( envresult1.stdout == 'uk' ) or ( envresult1.stdout == 'ldn' )

  - name: Activate Qualys Cloud Agent to APAC
    command: /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=c5c79f46-237a-430b-bfd9-96cbf7895d77 CustomerId=b546b3c9-3885-53eb-e040-18ac09046184 User=svcqca LogLevel=3 UseSudo=1 SudoUser=svcqca UserGroup=svcqca
    when: ( envresult1.stdout == 'hk' ) or ( envresult1.stdout == 'sg' )  or ( envresult1.stdout == 'sy')  or ( envresult1.stdout == 'au')

  - name: yum clean all
    command: /usr/bin/yum clean all

  - name: Qualys installer cleanup
    shell: rm /var/tmp/qualys-cloud-agent.x86_64.rpm

  - name: "Stop Qualys Agent"
    systemd:
      name: qualys-cloud-agent
      state: stopped
    when: osresult.stdout.split(".")[0] == "7"

  - name: "Ensure Qualys is disabled on startup"
    systemd:
      name: qualys-cloud-agent
      enabled: no
    when: osresult.stdout.split(".")[0] == "7"

  - name: restart chkconfig service
    service: name=qualys-cloud-agent state=stopped enabled=no
    when: osresult.stdout.split(".")[0] == "6"

  - name: Add cron job to start Qualys and perform manual scan and turn off after an hour
    become: true
    cron:
      name: "Qualys Cron Job"
      minute: "0"
      hour: "19"
      weekday: "6"
      user: svcqca
      job: "sudo systemctl start qualys-cloud-agent && sudo /usr/local/qualys/cloud-agent/bin/cloudagentctl.sh action=ondemand type=vm && sleep 3600 && sudo systemctl stop qualys-cloud-agent"
    when: osresult.stdout.split(".")[0] == "7"

  - name: Add cron job to start Qualys and perform manual scan and turn off after an hour
    become: true
    cron:
      name: "Qualys Cron Job"
      minute: "0"
      hour: "19"
      weekday: "6"
      user: svcqca
      job: "sudo service qualys-cloud-agent start && sudo /usr/local/qualys/cloud-agent/bin/cloudagentctl.sh action=ondemand type=vm && sleep 3600 && sudo service qualys-cloud-agent stop"
    when: osresult.stdout.split(".")[0] == "6"

#  - name: "Performing Qualys manual scan"
#    shell: /usr/local/qualys/cloud-agent/bin/cloudagentctl.sh action=demand type=vm

#  - name: Wait for one hour before stopping the Qualys process
#    pause:
#      minutes: 120

  - name: "Stopping Qualys service"
    shell: service qualys-cloud-agent stop

